add hyperlink
UnblockNeteaseMusic/luci-app-unblockneteasemusic pull request #93
Opened 2021-11-03 16:20 UTC by Beginner-Go

2021-11-03 22:34 UTC, pan93412 approved these changes

2021-11-04 07:50 UTC, 1715173329 requested changes
btw, if you would like to use hyperlink, please apply it to other urls as well.

2021-11-04 07:50 UTC, 1715173329 commented on luasrc/model/cbi/unblockneteasemusic/unblockneteasemusic.lua
> +mp.title = translate("解除网易云音乐播放限制")
```suggestion
mp = Map("unblockneteasemusic", translate("解除网易云音乐播放限制"))
```
Keep it as-is.

2021-11-04 07:50 UTC, 1715173329 commented on luasrc/model/cbi/unblockneteasemusic/unblockneteasemusic.lua
> +mp.description = translate("原理：采用 [Bilibili/JOOX/酷狗/酷我/咪咕/pyncmd/QQ/Youtube] 等音源，替换网易云音乐 无版权/收费 歌曲链接<br/>具体使用方法参见：<a href=\"https://github.com/UnblockNeteaseMusic/luci-app-unblockneteasemusic\" targe
```suggestion
mp.description = translate("原理：采用 [Bilibili/JOOX/酷狗/酷我/咪咕/pyncmd/QQ/Youtube] 等音源，替换网易云音乐 无版权/收费 歌曲链接<br/>具体使用方法参见：<a href=\"https://github.com/UnblockNeteaseMusic/luci-app-unblockneteasemusic\" target=\"_blank\">GitHub @UnblockNeteaseMusic/luci-app-unblockneteasemusic</a>")
```

2021-11-04 08:29 UTC, Beginner-Go commented
Has been changed to what you expected

2021-11-04 08:32 UTC, 1715173329 approved these changes

2021-11-04 08:33 UTC, merged